# Generated by Django 3.2.9 on 2022-01-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_NAME', models.CharField(max_length=40)),
                ('DESCRIPTION', models.TextField(max_length=100)),
                ('PRICE', models.BigIntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
