# Generated by Django 3.2.9 on 2022-01-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='Image',
        ),
        migrations.AddField(
            model_name='productdata',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
