# Generated by Django 3.2.9 on 2022-01-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20220121_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDER_ID', models.BigIntegerField()),
                ('PRODUCT_ID', models.BigIntegerField()),
                ('DATE', models.DateField()),
                ('PRICE', models.BigIntegerField()),
                ('QTY', models.CharField(max_length=100)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
